[
    {
        "domain": ".netflix.com",
        "expirationDate": 1695290597.076113,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-normal-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1719050595.160054,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SecureNetflixId",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v%3D2%26mac%3DAQEAEQABABST187lWvjhRzsrv3ylaOjWUS8TRmNNfKw.%26dt%3D1687514590208"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1695290597.076097,
        "hostOnly": false,
        "httpOnly": false,
        "name": "nkufi-normal-4-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1695290597.076105,
        "hostOnly": false,
        "httpOnly": false,
        "name": "nkufi-bold-4-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1687516444.810371,
        "hostOnly": false,
        "httpOnly": false,
        "name": "profilesNewSession",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "0"
    },
    {
        "domain": ".netflix.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "clSharedContext",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "ac5a4fa0-2a36-4b28-ad47-6ac5573e431d"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1719050595.160092,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NetflixId",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v%3D2%26ct%3DBQAOAAEBEDKHNzcHlEeaL1OGNlfl4rSBwNKA0kseduyqAIsTwEZOG6lOtSy2jHnqaDfN0IYoocPev5ywi35IGb3Y07wy1JXo4zTZrk8N6AJhsJ_f9OwVUnDLToMe8YYbM-6rBfCTcz4KNJNG9n9P6SHOdY4y1cftfHWlZwnWpZwgt-7NvwAC1X9HDjd2CD5IaoE9YLeh8ol2Q6WHv-O_O8WQX5IyJEg3V6vm5S8UFjnpssIm59PVhVX2WC0XThl_rTXxhxrkhE3WlgejBJf0Fm0uVOeBUxtOTxrBrd-9Tl-VC3G1VRRSt9VxtYO64sLNlKHDa1XjtFIDHQFuNC892-IPbkb4jXerURf9Np9pgvSz0E4ha_4p6Zgoy0nE3_BwUPTS-PrmojwDMTebMcdgTeBK2i9ExUGjtqQx6mivHK0lmspa2vbmwSQEfCfIjBILFBVZDHdLqcPDoL10BvV0ihlL2JBMDYeLv6LBlbNKpRWDJ0uMH4wqFKX1Dg-g59NcCn8saPvxKKla6QRcfPZhiRK08nNWs_kxshH1WYk5vnfiX-sQFlj1P0mDGuR2It2_Tvw3B3JwjLfsQdTRRDUL_CPvhhFYSXMaWts4uxbKeTmmezQZZGkNJYc.%26bt%3Ddbl%26ch%3DAQEAEAABABS7PMtB-RlyHck6NkQ1DupTG7LPC99YTgM.%26mac%3DAQEAEAABABQVv5wtGAoebkIq0IlmHxN4amG-s99DxG0."
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1695290597.076067,
        "hostOnly": false,
        "httpOnly": false,
        "name": "pas",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "%7B%22supplementals%22%3A%7B%22muted%22%3Atrue%7D%7D"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1719050597,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonConsent",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "isIABGlobal=false&datestamp=Fri+Jun+23+2023+17%3A03%3A17+GMT%2B0700+(Indochina+Time)&version=202301.1.0&consentId=d9aa1108-8001-4f25-ba39-47f0edb4b840&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1&hosts=&AwaitingReconsent=false&geolocation=AR%3BB&isGpcEnabled=0"
    },
    {
        "domain": ".www.netflix.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "cL",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "1643214371132%7C164321437165820792%7C16432143714232107%7C%7C154%7CWZKMURK4ANHNHNJI4NOS46VWBI"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1687525379.814298,
        "hostOnly": false,
        "httpOnly": false,
        "name": "flwssn",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fd818a0a-ac35-4cc3-a704-f1605793356a"
    },
    {
        "domain": ".netflix.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "memclid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "6456a6aa-0edb-40c2-bfdd-51ab8c2244c5"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1695290597.076121,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-bold-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "nfvdid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "BQFmAAEBEKgwQyXQIwGUMkguoZTbcuJg-zI7CX95t22gYalKNkB-ZoiJsv3H6Km0QwVcL4xt6ZVm7CRa5Le9GkvbezkiYjwQq_kJRzS3ooj8ITfBuTiKqT1q7fVvvEv0cCftcIMb0C_0B7L4OivQe1ktINd9ANTc"
    },
    {
        "domain": ".netflix.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonAlertBoxClosed",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "2022-05-04T13:07:55.556Z"
    }
]
