# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.netflix.com	TRUE	/	FALSE	1695751136	netflix-sans-normal-3-loaded	true
.netflix.com	TRUE	/	TRUE	1719511131	SecureNetflixId	v%3D2%26mac%3DAQEAEQABABTUQwAUVMldiHPFI1f4yZAe8CLFvBB3siQ.%26dt%3D1687975120018
.netflix.com	TRUE	/	FALSE	1695751136	nkufi-normal-4-loaded	true
.netflix.com	TRUE	/	FALSE	1695751136	nkufi-bold-4-loaded	true
.netflix.com	TRUE	/	FALSE	1695751136	hasSeenCookieDisclosure	true
.netflix.com	TRUE	/	FALSE	1687976934	profilesNewSession	0
.netflix.com	TRUE	/	TRUE	1719511131	NetflixId	v%3D2%26ct%3DBQAOAAEBEKfP6TliUMLRRRxQz2GnaTiB4It_pCTlKQ1Zb5wR2DsDrpnESBnjYFaZvzzRMrmMX-rjzQVuB7HMW1h-ZhNs2-j99sdw72LHPYa9GrNMdnSySAZ6wH6XPM5aH79nlkUOlO0lwD72YYe6VNliBHyI9U6fEk_hp4IQ-AvAMhKmYMSh7ECQRrHrjbmJfbMc-rs3o5eSsFJGpCP3JmGbzaDUWl1HmQGVK9-z_llkX_0TIX2qWu3J3FUVSp8gEvrxpLsNvw-iEg5NEvCzu3iBpXMOOeLsmCUWBjGv9ftcFuMPGFHzBlGq7pYZ93brPCrfT_Oi85PPLR_p_1qCvxhJsAyKbN_nAUGQphYmPNsuRSAALlJK_43aKEmdXNW0eTE0oRa34ZPAhG3MpwEhidH2zN45OiWOs4GMnjt2rm7bWhtgsyfPgbOXpJSSmtQ2UjRlavIAf09pKh0RKCypiQxnp2Fo8r-Ur0GNNpE-9QRE9_dZYdCKlgKhslVSKZTZC0Age26tMlTKUznL_8CqV_GZljb_9A_MHyUz6i271g1wNS9JlT0o7jZ0_QrI0t3iX_GyoVX5ph7fu3GckwM6pE7YrbsNCOTewRX4f3jo42L6DXyne8T2foMJXoikcgvUmqrjEQ_6oJ_FWAfaaSoaSbGOaGdJgNf9tA..%26bt%3Ddbl%26ch%3DAQEAEAABABTNRXoutHuvqK3hR2rddgu88HKxambZ6Sk.%26mac%3DAQEAEAABABSXYA6uvsHi3glZvw159h0X1SC4_wFFhvs.
.netflix.com	TRUE	/	FALSE	1695751136	pas	%7B%22supplementals%22%3A%7B%22muted%22%3Afalse%7D%7D
.netflix.com	TRUE	/	FALSE	1719511134	OptanonConsent	isIABGlobal=false&datestamp=Thu+Jun+29+2023+00%3A58%3A54+GMT%2B0700+(Indochina+Time)&version=202301.1.0&consentId=7414f3f4-a8dc-4194-bb4f-490840bb3daa&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A0&hosts=&AwaitingReconsent=false&geolocation=GB%3BENG&isGpcEnabled=0
.netflix.com	TRUE	/	FALSE	1687985931	flwssn	ebd36bcd-f6ed-463a-b8fb-3de785356569
.netflix.com	TRUE	/	FALSE	1695751136	netflix-sans-bold-3-loaded	true
.netflix.com	TRUE	/	FALSE	1719511131	nfvdid	BQFmAAEBEBBRGjPAXjTKwqX8lNfnNU1gwGSo2Xd2p-hhbj4Hz9yuD2p3lEyXDZ6loOQ22rYWXh3gB-xkWQzCd835AC6ccxOuLAMMZrZEvfj1nIrBMByVBDahT2p3nXnRgiOfPxFA4aTVqi1Vd_2Voy_9QElYwdM-
